name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y bc

      - name: Run tests
        run: |
          chmod +x jury/render-the-verdict.sh
          ./jury/render-the-verdict.sh
